dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install -r extra.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=colony setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
git:
  submodules: false
deploy:
  provider: pypi
  user: joamag
  password:
    secure: eZWqymjhTS6QEk+CDApN6tZA5Epf1eD10TZeGcWwcZdsfd9lnf7yiluqRT6QhM5E49XZP1zZezRE6Azmc+Un5wI8bx7efELMjFgg6g7UkRGem7erHEb9ikeOsYuvh9zunHXLKjrB9rfFdSn59pXixvGn/IA2fQGdefy9FVDMIqs=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
